

server.memory.pagecache.size=512M

server.default_listen_address=0.0.0.0
server.directories.plugins=/plugins
server.directories.logs=/logs
server.directories.import=/var/lib/neo4j/import
dbms.security.procedures.unrestricted=apoc.*,n10s.*
dbms.security.procedures.allowlist=apoc.*,n10s.*
dbms.connector.bolt.enabled=true
